---
- name: "Clean apt local cache"
  ansible.builtin.apt:
    clean: true

- name: Upgrade all packages (apt full-upgrade)
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
  become: true

- name: "Install required packages"
  ansible.builtin.apt:
    update_cache: true
    name: "{{ raspberry_pi_packages }}"
    state: present

- name: Update bootloader if Pi 4 or newer
  ansible.builtin.shell: rpi-eeprom-update
  become: true
  when: pi_specs.nick is defined and pi_specs.nick | int >= 4

- name: Apply bootloader update if Pi 4 or newer
  ansible.builtin.shell: rpi-eeprom-update -a
  become: true
  when: pi_specs.nick is defined and pi_specs.nick | int >= 4
