---
# Variables file of the raspberry_pi's role

# Raspberry Pi specifications
raspberry_pi_specs: "{{ lookup('file', 'files/raspberry_pi_specs.yml') | from_yaml }}"

raspberry_pi_tasks:
  intro:
    active: true
    tasks:
      - name: determine_pi_specs.yml
        active: true
  mandatory:
    active: "{{ do_mandatory | default(true) }}"
    tasks:
      - name: addiontional_packages.yml
        active: true
      - name: add_user.yml
        active: true
      - name: bash_conf_files.yml
        active: true
      - name: setup_zsh.yml
        active: true
      - name: log2ram.yml
        active: true
      - name: locale.yml
        active: true
      - name: timezone.yml
        active: true
      - name: disable_hdmi.yml
        active: "{{ headless is defined and headless is true | default(false) }}"
      - name: gpu_mem_split.yml
        active: true
      - name: samba.yml
        active: true
      - name: hostname.yml
        active: true
      - name: fan_control.yml
        active: true
  optional:
    active: "{{ do_optional | default(false) }}"
    tasks:
      - name: install_docker.yml
        # If the Raspberry Pi have ARMv6 CPU or higher, we can install Docker
        active: "{{ raspberry_pi_specs.processor is defined and 'ARMv6-compatible processor rev 7 (v6l)' not in raspberry_pi_specs.processor }}"
      - name: wordpress_docker-compose.yml
        active: false
      - name: install_sabnzbd.yml
        active: false
      - name: setup_dac.yml
        active: "{{ dac_usage is defined and dac_usage is true | default(false) }}"
      - name: set_hdparm_spindown.yml
        active: "{{ external_drive is true }}" # Skip if no external drive is defined in inventory host definition
  experimental:
    active: "{{ do_experimental | default(false) }}"
    tasks:

# Hostname configuration
# raspberry_pi_hostname_prefix: pi_
# raspberry_pi_hostname: "{{ force_hostname | default('pi') }}"

# First admin name:
raspberry_pi_first_admin: nico

# === Regional configuration (uncomment the desired group) ===
## France (default)
raspberry_pi_locale: "fr_FR.UTF-8"
raspberry_pi_timezone: "Europe/Paris"
raspberry_pi_keyboard: "fr"

## USA
# raspberry_pi_locale: "en_US.UTF-8"
# raspberry_pi_timezone: "America/New_York"
# raspberry_pi_keyboard: "us"

## UK
# raspberry_pi_locale: "en_GB.UTF-8"
# raspberry_pi_timezone: "Europe/London"
# raspberry_pi_keyboard: "uk"

## Germany
# raspberry_pi_locale: "de_DE.UTF-8"
# raspberry_pi_timezone: "Europe/Berlin"
# raspberry_pi_keyboard: "de"

## Spain
# raspberry_pi_locale: "es_ES.UTF-8"
# raspberry_pi_timezone: "Europe/Madrid"
# raspberry_pi_keyboard: "es"

## Italy
# raspberry_pi_locale: "it_IT.UTF-8"
# raspberry_pi_timezone: "Europe/Rome"
# raspberry_pi_keyboard: "it"

## China
# raspberry_pi_locale: "zh_CN.UTF-8"
# raspberry_pi_timezone: "Asia/Shanghai"
# raspberry_pi_keyboard: "us"  # Usually QWERTY

## Japan
# raspberry_pi_locale: "ja_JP.UTF-8"
# raspberry_pi_timezone: "Asia/Tokyo"
# raspberry_pi_keyboard: "jp"

# Additional packages to install
raspberry_pi_packages:
  - tzdata
  - git
  - tmux
  - vim
  - nmon
  - neofetch

# RAM size for log2ram folder in megabytes
raspberry_pi_log2ram_size: '128'

# Changes SSH port
# raspberry_pi_ssh_port : 28

# GPU memory split in megabytes
raspberry_pi_gpu_mem: '16' # 16, 64, 128 or 256

# Disable HDMI to preserve power
# raspberry_pi_disable_hdmi: true

# Disable IPv6 on specified interfaces
# raspberry_pi_disable_ipv6_interfaces:
#   - wlan0
#   - eth0

## Samba configuration
raspberry_pi_samba_packages:
  - samba-common
  - samba
  - samba-client

raspberry_pi_samba_services:
  - smbd
  - nmbd

raspberry_pi_samba_netbios_name: monserveur
raspberry_pi_samba_configuration_dir: /etc/samba
raspberry_pi_samba_configuration_template: smb.conf.j2
raspberry_pi_samba_conf_file: "{{ raspberry_pi_samba_configuration_dir }}/smb.conf"

raspberry_pi_sabnzbd: true

# Variables pour ZSH :
raspberry_pi_oh_my_zsh_url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
raspberry_pi_fzf_repo_url: "https://github.com/junegunn/fzf.git"
raspberry_pi_zsh_syntax_highlighting_url: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
raspberry_pi_zsh_autosuggestions_url: "https://github.com/zsh-users/zsh-autosuggestions.git"
raspberry_pi_zsh_custom_dir: "/home/{{ zsh_user }}/.zsh"

# HDPARAM configuration (parameter for the eventualy external drive)
raspberry_pi_sda_spindown: 120
